# Generated by Django 6.0.7 on 2026-08-27 15:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('predicted_emotion', models.CharField(choices=[('joy', 'Joy'), ('anger', 'Anger'), ('fear', 'Fear'), ('sadness', 'Sadness'), ('surprise', 'Surprise'), ('disgust', 'Disgust'), ('neutral', 'Neutral')], max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('all_scores', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
